INSERT INTO common_department (college, name, type, is_editable, has_advanced, code, member_count)
VALUES ('융합공과대학', '컴퓨터과학전공', 'BALANCE_ENGINEER', false, true, '03005', 0),
       ('융합공과대학', '전기공학전공', 'BALANCE_NATURAL', false, true, '03208', 0),
       ('융합공과대학', '지능IOT융합전공', 'BALANCE_ENGINEER', false, true, '03209', 0),
       ('융합공과대학', '게임전공', 'BALANCE_ENGINEER', false, true, '03006', 0),
       ('융합공과대학', '애니메이션전공', 'BALANCE_ART', false, true, '03007', 0),
       ('융합공과대학', '휴먼지능정보공학전공', 'BALANCE_ENGINEER', false, true, '03204', 0),
       ('융합공과대학', '핀테크전공', 'BALANCE_ENGINEER', true, true, '03205', 0),
       ('융합공과대학', '빅데이터융합전공', 'BALANCE_ENGINEER', true, true, '03206', 0),
       ('융합공과대학', '스마트생산전공', 'BALANCE_ENGINEER', true, true, '03207', 0),
       ('융합공과대학', '생명공학전공', 'BALANCE_NATURAL', false, true, '03000', 0),
       ('융합공과대학', '화학에너지공학전공', 'BALANCE_NATURAL', false, true, '03001', 0),
       ('융합공과대학', '화공신소재전공', 'BALANCE_NATURAL', false, true, '03002', 0),
       ('융합공과대학', '한일문화콘텐츠전공', 'BALANCE_HUMANITIES', false, true, '03008', 0),
       ('인문사회과학대학', '역사콘텐츠전공', 'BALANCE_HUMANITIES', false, true, '02988', 0),
       ('인문사회과학대학', '지적재산권전공', 'BALANCE_SOCIAL', false, true, '02989', 0),
       ('인문사회과학대학', '문헌정보학전공', 'BALANCE_SOCIAL', false, true, '02990', 0),
       ('인문사회과학대학', '공간환경학부', 'BALANCE_SOCIAL', false, true, '00962', 0),
       ('인문사회과학대학', '행정학부', 'BALANCE_SOCIAL', false, true, '03183', 0),
       ('인문사회과학대학', '가족복지학과', 'BALANCE_SOCIAL', false, true, '00951', 0),
       ('인문사회과학대학', '국가안보학과', 'BALANCE_HUMANITIES', false, true, '00964', 0),
       ('사범대학', '국어교육과', 'BALANCE_HUMANITIES', false, true, '00971', 0),
       ('사범대학', '영어교육과', 'BALANCE_HUMANITIES', false, true, '00972', 0),
       ('사범대학', '교육학과', 'BALANCE_HUMANITIES', false, true, '00975', 0),
       ('사범대학', '수학교육과', 'BALANCE_NATURAL', false, true, '00976', 0),
       ('경영경제대학', '경제금융학부', 'BALANCE_SOCIAL', false, true, '01178', 0),
       ('경영경제대학', '경영학부', 'BALANCE_SOCIAL', false, true, '01179', 0),
       ('경영경제대학', '글로벌경영학과', 'BALANCE_SOCIAL', false, true, '01180', 0),
       ('경영경제대학', '융합경영학과', 'BALANCE_SOCIAL', false, false, '01181', 0),
       ('문화예술대학', '식품영양학전공', 'BALANCE_NATURAL', false, true, '02994', 0),
       ('문화예술대학', '의류학전공', 'BALANCE_NATURAL', false, true, '02995', 0),
       ('문화예술대학', '스포츠건강관리전공', 'BALANCE_ART', false, true, '02997', 0),
       ('문화예술대학', '무용예술전공', 'BALANCE_ART', false, true, '02998', 0),
       ('문화예술대학', '조형예술전공', 'BALANCE_ART', false, true, '02991', 0),
       ('문화예술대학', '생활예술전공', 'BALANCE_ART', false, true, '02992', 0),
       ('문화예술대학', '음악학부', 'BALANCE_ART', false, true, '01132', 0);

COMMIT;
